### ISSUE TITLE
[Plugins] General Plugin API

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/vigour-native#115]
# General Plugin API

The goal this Plugin Spec is to have things shared between platforms, and to do as much as possible through setting properties, resulting in Observable values, which connect directly to the rest of the stack. It's still possible (and in some cases it might make more sense) to implement functions with callbacks, but we should opt for the property style when sane.

![general Plugin overview](https://www.lucidchart.com/publicSegments/view/5765d17c-21fb-4a36-9435-11fa5905b97d/image.png)

### Sets are passed to the bridge

Every native Plugin will take the form of an `Observable` on the JavaScript side, that is connected to the `vigour-wrapper/bridge`.
Whenever a property is changed on the Observable, a `set` signal (including `path` and `value`) is sent over the bridge, and received on the native side.

### Conditions

The only other responsibility of the JavaScript side is to provide `conditions` when needed. They can be used to
- conditionally block value changes going to the bridge
- conditionally block value changes coming from the bridge

### Bridge passes sets to Plugins

Based on the `set` signal the bridge receives, it grabs the targeted Plugin and passes it the set.

#### Plugins pass sets to "subscribed" functions / a.k.a. event listeners

The Plugin will then check if there are functions "subscribed" to a pattern that matches `path`, and call these functions passing the `path`, `value` and a reference to the Plugin.

| Plugin | pattern | function |
| --- | --- | --- |
| ChromeCast | session | sessionChange |
| Pay | items.*.purchased | pruchaseItem  | 

### Plugin.set (called by native functions) passes sets back to bridge

Whenever any native function (could be the `init` function) needs to pass information back to the JavaScript side, it will call Plugin.set, with a `path` and a `value`.

e.g.

ChromeCast:
```javascript
var path = ['devices', device.id]
var value = {
  name: device.friendlyName,
  id: device.id
}

ChromeCastPlaugin.set(path, value)
```

Orientation:
```java
OrientationPlugin.set('landscape') // sets OrientationPlugin.val = 'landscape'
```

### Bridge applies sets to Javascript side Observable

The bridge then makes sure that these sets are applied to the Observable on the JavaScript side.

**Comment by marcusbesjes** [comment]
@shawninder I'd like to discuss with you exactly what parts are already in place

**Comment by shawninder** [comment]
@marcusbesjes Are you intentionally breaking the pattern with the orientation plugin whose set function takes a single argument instead of two?

We could have something more similar with `OrientationPlugin.set('current', 'landscape') // sets OrientationPlugin.current.val = 'landscape'`. Of course the `current` thing is kind of useless, but at least we have the same pattern across plugins...

**Comment by shawninder** [comment]
@renancarvalho I think you should also be aware of this. Ask me or Marcus for more details on this

**Comment by marcusbesjes** [comment]
We have decided not to go this route, we just work with methods and events!
